- name: include ubntu.yml settings file
  include_tasks: tasks/debian.yml
  when: ansible_os_family|lower == "debian"

- name: include redhat.yml settings file
  include_tasks: tasks/redhat.yml
  when: ansible_os_family|lower == "redhat"
